# Generated by Django 4.2.5 on 2023-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_experto_prevencion_riesgos', models.CharField(blank=True, max_length=255, null=True)),
                ('nro_trabajadores_empresa', models.IntegerField(blank=True, null=True)),
                ('numero_de_contrato', models.CharField(blank=True, db_column='Numero_de_Contrato', max_length=255, null=True)),
                ('gerencia', models.CharField(blank=True, db_column='Gerencia', max_length=255, null=True)),
                ('superintendencia', models.CharField(blank=True, db_column='Superintendencia', max_length=255, null=True)),
                ('nombre_admin_contrato_antucoya', models.CharField(blank=True, db_column='Nombre_Admin_Contrato_Antucoya', max_length=255, null=True)),
                ('nombre_admin_contrato_empresa_contratista', models.CharField(blank=True, db_column='Nombre_Admin_Contrato_Empresa_Contratista', max_length=255, null=True)),
                ('correo_admin_ec', models.CharField(blank=True, db_column='Correo_Admin_EC', max_length=255, null=True)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio_evaluacion', models.DateField(blank=True, null=True)),
                ('fecha_termino_evaluacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsEvaluacion',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('item_a_evaluar', models.TextField(blank=True, null=True)),
                ('marco_legal', models.TextField(blank=True, null=True)),
                ('evidencia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'items_evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oportunidadmejora',
            fields=[
                ('id_oportunidad', models.IntegerField(primary_key=True, serialize=False)),
                ('actividad', models.CharField(db_column='Actividad', max_length=255)),
                ('porcentajeavance', models.DecimalField(db_column='PorcentajeAvance', decimal_places=2, max_digits=5)),
                ('responsable', models.CharField(db_column='Responsable', max_length=255)),
                ('fechainicio', models.DateField(db_column='FechaInicio')),
                ('fechatermino', models.DateField(db_column='FechaTermino')),
            ],
            options={
                'db_table': 'oportunidadmejora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Protocolos',
            fields=[
                ('id_protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=125)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'protocolos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Protocolosseleccionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'protocolosseleccionados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResultadosEvaluacion',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('porcentaje_cumplimiento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('items_cumplidos', models.IntegerField(blank=True, null=True)),
                ('items_no_cumplidos', models.IntegerField(blank=True, null=True)),
                ('items_no_aplicaron', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resultados_evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TitulosRequisitos',
            fields=[
                ('id_titulo', models.AutoField(primary_key=True, serialize=False)),
                ('numero_item', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_grupo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'titulos_requisitos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('apellido_paterno_usuario', models.CharField(max_length=255)),
                ('apellido_materno_usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('email_usuario', models.CharField(max_length=255)),
                ('clave_usuario', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
