# Generated by Django 4.2.5 on 2023-11-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
