# Generated by Django 4.2.5 on 2023-11-16 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_empresas_fecha_creacion'),
        ('accounts', '0002_empresainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresas'),
        ),
        migrations.DeleteModel(
            name='EmpresaInfo',
        ),
    ]
